server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: Employee Management System
  datasource:
    username: ${DB_USER:ems}
    url: ${DB_URL:jdbc:h2:mem:ems-test}
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'